// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBATZSbtz9mH2BG17cGCIQKa4eK4jbplHg',
    appId: '1:1013315022277:web:f7c3aad8bbafc843e7afac',
    messagingSenderId: '1013315022277',
    projectId: 'student-suite2',
    authDomain: 'student-suite2.firebaseapp.com',
    storageBucket: 'student-suite2.firebasestorage.app',
    measurementId: 'G-4DNXHGNCM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArFhh9b4WPdHuL65aOWtABOWaFAR535sg',
    appId: '1:1013315022277:android:adb26e66c63ab66fe7afac',
    messagingSenderId: '1013315022277',
    projectId: 'student-suite2',
    storageBucket: 'student-suite2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxtUkDpwyunZWe9Er1CA-Jh2NoK0z7nLk',
    appId: '1:1013315022277:ios:6a649f74f047de2de7afac',
    messagingSenderId: '1013315022277',
    projectId: 'student-suite2',
    storageBucket: 'student-suite2.firebasestorage.app',
    iosBundleId: 'com.pegumax.studentsuite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxtUkDpwyunZWe9Er1CA-Jh2NoK0z7nLk',
    appId: '1:1013315022277:ios:57cf2abb10695ee8e7afac',
    messagingSenderId: '1013315022277',
    projectId: 'student-suite2',
    storageBucket: 'student-suite2.firebasestorage.app',
    iosBundleId: 'com.example.studentSuite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_S9XYNUMJVeUcGsZmKYvrDDag8dAY8cQ',
    appId: '1:1013315022277:web:83132590692f10c4e7afac',
    messagingSenderId: '1013315022277',
    projectId: 'student-suite2',
    authDomain: 'student-suite2.firebaseapp.com',
    storageBucket: 'student-suite2.firebasestorage.app',
    measurementId: 'G-DQ0J6MD9S7',
  );
}
